default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: examenCertificacion_AdolfoAlvarez_development
  username: <%= ENV['userdb'] %>
  password: <%= ENV['passworddb'] %>

test:
  <<: *default
  database: examenCertificacion_AdolfoAlvarez_test
  username: <%= ENV['userdb'] %>
  password: <%= ENV['passworddb'] %>

production:
  <<: *default
  database: examenCertificacion_AdolfoAlvarez_production
  username: examenCertificacion_AdolfoAlvarez
  password: <%= ENV["EXAMENCERTIFICACION_ADOLFOALVAREZ_DATABASE_PASSWORD"] %>
